name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  JUCE_VERSION: '8.0.8'
  PLUGINVAL_VERSION: '1.0.0'

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
        config: [Debug, Release]
        include:
          - platform: macos-latest
            os: macOS
            arch: universal
          - platform: windows-latest
            os: Windows
            arch: x64
          - platform: ubuntu-latest
            os: Linux
            arch: x64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JUCE
        uses: juce-framework/juce-setup@v1
        with:
          version: ${{ env.JUCE_VERSION }}

      - name: Cache JUCE
        uses: actions/cache@v4
        with:
          path: |
            ~/.juce
            ${{ github.workspace }}/JuceLibraryCode
          key: juce-${{ env.JUCE_VERSION }}-${{ runner.os }}

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            build/
            Builds/VisualStudio2022/x64/${{ matrix.config }}/
            Builds/LinuxMakefile/build/
          key: build-${{ runner.os }}-${{ matrix.config }}-${{ hashFiles('**/*.cpp', '**/*.h', '**/*.jucer') }}

      - name: Setup build environment
        if: matrix.os == 'macOS'
        run: |
          # Create self-signed certificate for code signing
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain
          
          # Create certificate
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=UltraDYN Development"
          openssl pkcs12 -export -out certificate.p12 -inkey key.pem -in cert.pem -passout pass:""
          
          # Import certificate
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

      - name: Build project
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            # macOS build
            xcodebuild -project Builds/MacOSX/ultraDYN.xcodeproj -scheme ultraDYN -configuration ${{ matrix.config }} -derivedDataPath build
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            # Windows build
            msbuild Builds/VisualStudio2022/ultraDYN.sln /p:Configuration=${{ matrix.config }} /p:Platform=x64
          else
            # Linux build
            make -C Builds/LinuxMakefile CONFIG=${{ matrix.config }}
          fi

      - name: Setup pluginval
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_macOS.zip"
            unzip pluginval.zip
            chmod +x pluginval
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_Windows.zip"
            unzip pluginval.zip
          else
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_Linux.zip"
            unzip pluginval.zip
            chmod +x pluginval
          fi

      - name: Validate plugins
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            ./pluginval --validate-in-process --timeout-ms 60000 build/Build/Products/${{ matrix.config }}/ultraDYN.vst3
            ./pluginval --validate-in-process --timeout-ms 60000 build/Build/Products/${{ matrix.config }}/ultraDYN.component
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            ./pluginval.exe --validate-in-process --timeout-ms 60000 Builds/VisualStudio2022/x64/${{ matrix.config }}/VST3/ultraDYN.vst3
          else
            ./pluginval --validate-in-process --timeout-ms 60000 Builds/LinuxMakefile/build/ultraDYN.so
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ultraDYN-${{ matrix.os }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/Build/Products/${{ matrix.config }}/*.vst3
            build/Build/Products/${{ matrix.config }}/*.component
            build/Build/Products/${{ matrix.config }}/*.app
            Builds/VisualStudio2022/x64/${{ matrix.config }}/VST3/*.vst3
            Builds/VisualStudio2022/x64/${{ matrix.config }}/Standalone/*.exe
            Builds/LinuxMakefile/build/*.so
            Builds/LinuxMakefile/build/ultraDYN
          retention-days: 30
