name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

env:
  JUCE_VERSION: '8.0.8'
  PLUGINVAL_VERSION: '1.0.0'

jobs:
  build-and-release:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
        include:
          - platform: macos-latest
            os: macOS
            arch: universal
          - platform: windows-latest
            os: Windows
            arch: x64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JUCE
        shell: bash
        run: |
          # Download and setup JUCE framework
          JUCE_DIR="$HOME/juce"
          mkdir -p "$JUCE_DIR"
          cd "$JUCE_DIR"
          
          # Clone JUCE repository
          git clone --depth 1 --branch ${{ env.JUCE_VERSION }} https://github.com/juce-framework/JUCE.git .
          
          # Set JUCE path for the build
          echo "JUCE_DIR=$JUCE_DIR" >> $GITHUB_ENV

      - name: Cache JUCE
        uses: actions/cache@v4
        with:
          path: |
            $HOME/juce
            ${{ github.workspace }}/JuceLibraryCode
          key: juce-${{ env.JUCE_VERSION }}-${{ runner.os }}

      - name: Setup Visual Studio (Windows)
        if: matrix.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Check project files
        shell: bash
        run: |
          # Check if project files exist and are up to date
          echo "Checking project files..."
          if [ "${{ matrix.os }}" = "macOS" ]; then
            if [ -f "Builds/MacOSX/ultraDYN.xcodeproj/project.pbxproj" ]; then
              echo "Xcode project exists"
            else
              echo "Warning: Xcode project not found"
            fi
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            if [ -f "Builds/VisualStudio2022/ultraDYN.sln" ]; then
              echo "Visual Studio project exists"
            else
              echo "Warning: Visual Studio project not found"
            fi
          fi

      - name: Setup build environment
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          # Create self-signed certificate for code signing
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain
          
          # Create certificate with proper password handling
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=UltraDYN Development"
          openssl pkcs12 -export -out certificate.p12 -inkey key.pem -in cert.pem -passout pass:password
          
          # Import certificate with correct password
          security import certificate.p12 -k build.keychain -P password -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

      - name: Build project
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            # macOS build - use ultraDYN.jucer
            echo "Building macOS project..."
            xcodebuild -project Builds/MacOSX/ultraDYN.xcodeproj -scheme ultraDYN -configuration Release -derivedDataPath build -allowProvisioningUpdates
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            # Windows build - use ultraDYN.jucer
            echo "Building Windows project..."
            msbuild Builds/VisualStudio2022/ultraDYN.sln /p:Configuration=Release /p:Platform=x64 /verbosity:minimal
          fi

      - name: Setup pluginval
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_macOS.zip"
            unzip pluginval.zip
            chmod +x pluginval
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_Windows.zip"
            unzip pluginval.zip
          fi

      - name: Validate plugins
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            echo "Validating macOS plugins..."
            if [ -f "build/Build/Products/Release/ultraDYN.vst3" ]; then
              ./pluginval --validate-in-process --timeout-ms 60000 build/Build/Products/Release/ultraDYN.vst3
            else
              echo "Warning: VST3 plugin not found"
            fi
            if [ -f "build/Build/Products/Release/ultraDYN.component" ]; then
              ./pluginval --validate-in-process --timeout-ms 60000 build/Build/Products/Release/ultraDYN.component
            else
              echo "Warning: Audio Unit plugin not found"
            fi
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            echo "Validating Windows plugins..."
            if [ -f "Builds/VisualStudio2022/x64/Release/VST3/ultraDYN.vst3" ]; then
              ./pluginval.exe --validate-in-process --timeout-ms 60000 Builds/VisualStudio2022/x64/Release/VST3/ultraDYN.vst3
            else
              echo "Warning: VST3 plugin not found"
            fi
          fi

      - name: Create DMG (macOS only)
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          # Create DMG installer
          VERSION=${GITHUB_REF#refs/tags/}
          create-dmg \
            --volname "UltraDYN $VERSION" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "ultraDYN.app" 200 190 \
            --hide-extension "ultraDYN.app" \
            --app-drop-link 600 185 \
            "ultraDYN-$VERSION-macOS.dmg" \
            "build/Build/Products/Release/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ultraDYN-${{ matrix.os }}-${{ github.ref_name }}
          path: |
            build/Build/Products/Release/*.vst3
            build/Build/Products/Release/*.component
            build/Build/Products/Release/*.app
            Builds/VisualStudio2022/x64/Release/VST3/*.vst3
            Builds/VisualStudio2022/x64/Release/Standalone/*.exe
            ultraDYN-*-macOS.dmg

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.vst3
            artifacts/**/*.component
            artifacts/**/*.app
            artifacts/**/*.exe
            artifacts/**/*.dmg
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
