name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

env:
  JUCE_VERSION: '8.0.8'
  PLUGINVAL_VERSION: '1.0.0'

jobs:
  build-and-release:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
        include:
          - platform: macos-latest
            os: macOS
            arch: universal
          - platform: windows-latest
            os: Windows
            arch: x64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JUCE
        shell: bash
        run: |
          # Download and setup JUCE framework
          JUCE_DIR="$HOME/juce"
          mkdir -p "$JUCE_DIR"
          cd "$JUCE_DIR"
          
          # Clone JUCE repository
          git clone --depth 1 --branch ${{ env.JUCE_VERSION }} https://github.com/juce-framework/JUCE.git .
          
          # Set JUCE path for the build
          echo "JUCE_DIR=$JUCE_DIR" >> $GITHUB_ENV
          
          # Verify JUCE setup
          echo "JUCE directory contents:"
          ls -la
          echo "JUCE extras directory contents:"
          ls -la extras/ || echo "extras directory not found"
          echo "JUCE Projucer directory contents:"
          ls -la extras/Projucer/ || echo "Projucer directory not found"

      - name: Cache JUCE
        uses: actions/cache@v4
        with:
          path: |
            $HOME/juce
            ${{ github.workspace }}/JuceLibraryCode
          key: juce-${{ env.JUCE_VERSION }}-${{ runner.os }}

      - name: Build Projucer (macOS)
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          echo "Building Projucer..."
          xcodebuild -project "$JUCE_DIR/extras/Projucer/Builds/MacOSX/Projucer.xcodeproj" -scheme Projucer -configuration Release -derivedDataPath "$JUCE_DIR/extras/Projucer/Builds/MacOSX/build"
          PROJUCER_BIN="$JUCE_DIR/extras/Projucer/Builds/MacOSX/build/Build/Products/Release/Projucer.app/Contents/MacOS/Projucer"
          if [ ! -x "$PROJUCER_BIN" ]; then
            echo "Projucer binary not found at $PROJUCER_BIN"; ls -R "$JUCE_DIR/extras/Projucer/Builds/MacOSX/build/Build/Products" || true; exit 1
          fi
          echo "PROJUCER_BIN=$PROJUCER_BIN" >> $GITHUB_ENV

      - name: Setup Visual Studio (Windows)
        if: matrix.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Projucer (Windows)
        if: matrix.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Building Projucer..."
          $projucerSln = Join-Path $env:JUCE_DIR 'extras/Projucer/Builds/VisualStudio2022/Projucer.sln'
          if (!(Test-Path $projucerSln)) { Write-Error "Projucer solution not found at $projucerSln"; exit 1 }
          msbuild $projucerSln "/p:Configuration=Release" "/p:Platform=x64" "/verbosity:minimal"
          $projucerBin = Get-ChildItem -Path (Join-Path $env:JUCE_DIR 'extras/Projucer') -Recurse -Filter Projucer.exe | Select-Object -First 1
          if ($null -eq $projucerBin) { Write-Error "Projucer.exe not found after build"; exit 1 }
          echo "PROJUCER_BIN=$($projucerBin.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding ascii

      - name: Configure Projucer module paths and resave project
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            "$PROJUCER_BIN" --set-global-search-path osx defaultJuceModulePath="$JUCE_DIR/modules"
            "$PROJUCER_BIN" --resave ultraDYN.jucer
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            pwsh -Command '"$env:PROJUCER_BIN" --set-global-search-path windows defaultJuceModulePath="${env:JUCE_DIR}\modules"'
            pwsh -Command '"$env:PROJUCER_BIN" --resave ultraDYN.jucer'
          fi

      - name: Check project files
        shell: bash
        run: |
          # Check if project files exist and are up to date
          echo "Checking project files..."
          if [ "${{ matrix.os }}" = "macOS" ]; then
            if [ -f "Builds/MacOSX/ultraDYN.xcodeproj/project.pbxproj" ]; then
              echo "Xcode project exists"
            else
              echo "Warning: Xcode project not found"
            fi
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            if [ -f "Builds/VisualStudio2022/ultraDYN.sln" ]; then
              echo "Visual Studio project exists"
            else
              echo "Warning: Visual Studio project not found"
            fi
          fi

      - name: Verify build tools (Windows)
        if: matrix.os == 'Windows'
        shell: bash
        run: |
          echo "Checking available build tools..."
          echo "PATH: $PATH"
          echo "MSBuild location:"
          which msbuild || echo "msbuild not found in PATH"
          echo "Visual Studio installation:"
          ls -la "C:/Program Files/Microsoft Visual Studio/" || echo "Visual Studio not found"
          echo "Build Tools installation:"
          ls -la "C:/Program Files (x86)/Microsoft Visual Studio/" || echo "Build Tools not found"

      - name: Setup build environment
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          # Create self-signed certificate for code signing
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain
          
          # Create certificate with proper password handling
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=UltraDYN Development"
          openssl pkcs12 -export -out certificate.p12 -inkey key.pem -in cert.pem -passout pass:password
          
          # Import certificate with correct password
          security import certificate.p12 -k build.keychain -P password -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

      - name: Verify project configuration (macOS)
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          # Verify that project files are configured correctly for VST3 and AU only
          echo "Verifying project configuration..."
          
          if [ -f "Builds/MacOSX/ultraDYN.xcodeproj/project.pbxproj" ]; then
            echo "Xcode project exists"
            # List available schemes
            echo "Available schemes:"
            xcodebuild -project Builds/MacOSX/ultraDYN.xcodeproj -list
          else
            echo "Warning: Xcode project not found"
          fi

      - name: Build project (macOS)
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          # macOS build - build only VST3 and AU targets
          echo "Building macOS project..."
          
          # Build VST3 target only
          echo "Building VST3..."
          xcodebuild -project Builds/MacOSX/ultraDYN.xcodeproj -target "ultraDYN - VST3" -configuration Release -allowProvisioningUpdates -skipPackagePluginValidation
          
          # Build AU target only  
          echo "Building AU..."
          xcodebuild -project Builds/MacOSX/ultraDYN.xcodeproj -target "ultraDYN - AU" -configuration Release -allowProvisioningUpdates -skipPackagePluginValidation

      - name: Fix JUCE paths (Windows)
        if: matrix.os == 'Windows'
        shell: pwsh
        run: |
          # Fix JUCE paths in existing project files
          Write-Host "Fixing JUCE paths in project files..."
          
          # Use the correct JUCE directory path for Windows CI environment
          $juceDir = "C:\Users\runneradmin\juce"
          Write-Host "Using JUCE directory: $juceDir"
          
          # Verify JUCE directory exists
          if (Test-Path $juceDir) {
            Write-Host "JUCE directory exists: $juceDir"
            Write-Host "JUCE directory contents:"
            Get-ChildItem $juceDir -Name | Select-Object -First 10
          } else {
            Write-Host "Warning: JUCE directory does not exist: $juceDir"
            # Try alternative paths
            $altPaths = @("$env:HOME\juce", "C:\juce", "D:\juce")
            foreach ($path in $altPaths) {
              if (Test-Path $path) {
                $juceDir = $path
                Write-Host "Found JUCE at alternative path: $juceDir"
                break
              }
            }
          }
          
          # Set JUCE_PATH environment variable for MSBuild
          $env:JUCE_PATH = $juceDir
          Write-Host "Set JUCE_PATH environment variable to: $env:JUCE_PATH"
          
          # Check if project files exist and update JUCE paths
          if (Test-Path "Builds\VisualStudio2022\ultraDYN.vcxproj") {
            Write-Host "Found existing project files, updating JUCE paths..."
            
            # Read the project file
            $projectContent = Get-Content "Builds\VisualStudio2022\ultraDYN.vcxproj" -Raw
            
            # Replace JUCE_PATH references with the correct CI environment path
            $projectContent = $projectContent -replace '\$\(JUCE_PATH\)', $juceDir
            
            # Write back the updated project file
            Set-Content "Builds\VisualStudio2022\ultraDYN.vcxproj" $projectContent -NoNewline
            
            Write-Host "Updated JUCE paths in project file"
          } else {
            Write-Host "Warning: Project files not found"
          }

      - name: Build project (Windows)
        if: matrix.os == 'Windows'
        shell: pwsh
        run: |
          # Windows build using PowerShell - build only VST3 target
          Write-Host "Building Windows project (VST3 only)..."
          
          # Find MSBuild
          $msbuildPath = $null
          $possiblePaths = @(
            "msbuild",
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe",
            "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe",
            "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"
          )
          
          foreach ($path in $possiblePaths) {
            if (Get-Command $path -ErrorAction SilentlyContinue) {
              $msbuildPath = $path
              break
            }
          }
          
          if ($msbuildPath) {
            Write-Host "Using MSBuild at: $msbuildPath"
            # Build the ultraDYN project
            & $msbuildPath "Builds\VisualStudio2022\ultraDYN.sln" "/p:Configuration=Release" "/p:Platform=x64" "/verbosity:minimal" "/t:ultraDYN"
          } else {
            Write-Error "MSBuild not found. Please ensure Visual Studio or Build Tools are installed."
            exit 1
          }

      - name: Setup pluginval
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_macOS.zip"
            unzip pluginval.zip
            chmod +x pluginval
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            curl -L -o pluginval.zip "https://github.com/Tracktion/pluginval/releases/download/v${{ env.PLUGINVAL_VERSION }}/pluginval_Windows.zip"
            unzip pluginval.zip
          fi

      - name: Validate plugins
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macOS" ]; then
            echo "Validating macOS plugins..."
            if [ -f "build/Build/Products/Release/ultraDYN.vst3" ]; then
              ./pluginval --validate-in-process --timeout-ms 60000 build/Build/Products/Release/ultraDYN.vst3
            else
              echo "Warning: VST3 plugin not found"
            fi
            if [ -f "build/Build/Products/Release/ultraDYN.component" ]; then
              ./pluginval --validate-in-process --timeout-ms 60000 build/Build/Products/Release/ultraDYN.component
            else
              echo "Warning: Audio Unit plugin not found"
            fi
          elif [ "${{ matrix.os }}" = "Windows" ]; then
            echo "Validating Windows plugins..."
            if [ -f "Builds/VisualStudio2022/x64/Release/VST3/ultraDYN.vst3" ]; then
              ./pluginval.exe --validate-in-process --timeout-ms 60000 Builds/VisualStudio2022/x64/Release/VST3/ultraDYN.vst3
            else
              echo "Warning: VST3 plugin not found"
            fi
          fi

      - name: Create DMG (macOS only)
        if: matrix.os == 'macOS'
        shell: bash
        run: |
          # Create DMG installer containing VST3 and AU only
          brew install create-dmg
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir -p dist/macos
          cp -R build/Build/Products/Release/*.vst3 dist/macos/ 2>/dev/null || true
          cp -R build/Build/Products/Release/*.component dist/macos/ 2>/dev/null || true
          create-dmg \
            --volname "UltraDYN $VERSION" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            "ultraDYN-$VERSION-macOS.dmg" \
            "dist/macos"

      - name: Create Windows Installer
        if: matrix.os == 'Windows'
        shell: bash
        run: |
          # Create Windows installer using NSIS, packaging VST3 only
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Creating Windows installer for version $VERSION"
          choco install nsis -y
          mkdir -p dist/windows
          cp -r "Builds/VisualStudio2022/x64/Release/VST3/"* dist/windows/ 2>/dev/null || true
          makensis /DVERSION="$VERSION" /DVST3SOURCE="dist/windows" /DPRODUCT_NAME="ultraDYN" installer/windows.nsi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ultraDYN-${{ matrix.os }}-${{ github.ref_name }}
          path: |
            build/Build/Products/Release/*.vst3
            build/Build/Products/Release/*.component
            Builds/VisualStudio2022/x64/Release/VST3/*.vst3
            ultraDYN-*-macOS.dmg
            ultraDYN-*-Windows-Setup.exe

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.vst3
            artifacts/**/*.component
            artifacts/**/*.dmg
            artifacts/**/*Windows-Setup.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
